[package]
name = "legado-runtime"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[features]
rquickjs-bindgen = ["rquickjs/bindgen"]

[dependencies]
anyhow.workspace = true
aes.workspace = true
base64.workspace = true
cbc.workspace = true
chrono.workspace = true
des.workspace = true
ego-tree.workspace = true
encoding_rs.workspace = true
hanconv.workspace = true
hex.workspace = true
hmac.workspace = true
lol_html.workspace = true
sha1.workspace = true
sha2.workspace = true
md5.workspace = true
percent-encoding.workspace = true
publicsuffix.workspace = true
rar.workspace = true
regex.workspace = true
reqwest.workspace = true
rquickjs.workspace = true
roxmltree.workspace = true
rsa.workspace = true
rusqlite.workspace = true
scraper.workspace = true
serde.workspace = true
serde_json.workspace = true
sevenz-rust2.workspace = true
thiserror.workspace = true
ttf-parser.workspace = true
url.workspace = true
uuid.workspace = true
zip.workspace = true

[dev-dependencies]
tempfile = "3"
